name: Push and Hourly Workflow

on:
  push:
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora

jobs:
  run-example:
    runs-on: ubuntu-latest

    steps:
      # Action pré-existente: checkout do código-fonte
      - name: Checkout do código
        uses: actions/checkout@v3

      # Script personalizado: simulação de tarefa
      - name: Executar script personalizado
        run: |
          echo "Iniciando tarefa personalizada..."
          echo "Executando análise de código..."
          # Simule aqui o que quiser, como testes ou validações
          echo "Tarefa concluída com sucesso!"
